
---
logging:
   level:
     com.example: DEBUG

server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todos
    username: todo_user
    password: secret
  jpa:
    generate-ddl: true 
    
management:
  security:
    enabled: false